### ISSUE TITLE
User Favorites Story

### ISSUE THREAD

**Issue by DavidsRepos** [DavidsRepos/Project1#10]
User can save their search and data is persistent in db

- [x] User clicks Fav and search data, i.e. band, city, date is written to Firebase
- [x] page revisits read search data from db to present in HTML

**Comment by ArmiLawrence** [comment]
Story is linked with #19

**Comment by ArmiLawrence** [comment]
@ShelbySinz Hi Shelby, I am assigning this to you as this is linked with the DB logic you've been slaving away with. Thanks!
